#############################################################################
# Makefile for building: bin/canaveral
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  canaveral.pro
# Template: app
# Command: /usr/local/qt5/bin/qmake -o Makefile canaveral.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/usr/local/qt5/include -I/usr/local/qt5/include/QtWidgets -I/usr/local/qt5/include/QtGui -I/usr/local/qt5/include/QtCore -I.moc -I/usr/local/qt5/mkspecs/linux-g++
QMAKE         = /usr/local/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = canaveral1.0.0
DISTDIR = /home/victor/Documents/canaveral/.obj/canaveral1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/qt5/lib
LIBS          = $(SUBLIBS) -L/usr/local/qt5/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = .obj/

####### Files

SOURCES       = src/backend.cpp \
		src/buttons_tab.cpp \
		src/frontend.cpp \
		src/main.cpp \
		src/pad.cpp \
		src/samples_tab.cpp \
		src/volume_tab.cpp \
		src/select_window.cpp \
		src/sample.cpp \
		src/wav_parser.cpp .moc/moc_pad.cpp \
		.moc/moc_samples_tab.cpp \
		.moc/moc_select_window.cpp
OBJECTS       = .obj/backend.o \
		.obj/buttons_tab.o \
		.obj/frontend.o \
		.obj/main.o \
		.obj/pad.o \
		.obj/samples_tab.o \
		.obj/volume_tab.o \
		.obj/select_window.o \
		.obj/sample.o \
		.obj/wav_parser.o \
		.obj/moc_pad.o \
		.obj/moc_samples_tab.o \
		.obj/moc_select_window.o
DIST          = /usr/local/qt5/mkspecs/features/spec_pre.prf \
		/usr/local/qt5/mkspecs/common/unix.conf \
		/usr/local/qt5/mkspecs/common/linux.conf \
		/usr/local/qt5/mkspecs/common/sanitize.conf \
		/usr/local/qt5/mkspecs/common/gcc-base.conf \
		/usr/local/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/qt5/mkspecs/common/g++-base.conf \
		/usr/local/qt5/mkspecs/common/g++-unix.conf \
		/usr/local/qt5/mkspecs/qconfig.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/qt5/mkspecs/features/qt_functions.prf \
		/usr/local/qt5/mkspecs/features/qt_config.prf \
		/usr/local/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/local/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/local/qt5/mkspecs/features/default_pre.prf \
		/usr/local/qt5/mkspecs/features/resolve_config.prf \
		/usr/local/qt5/mkspecs/features/default_post.prf \
		/usr/local/qt5/mkspecs/features/warn_on.prf \
		/usr/local/qt5/mkspecs/features/qt.prf \
		/usr/local/qt5/mkspecs/features/resources.prf \
		/usr/local/qt5/mkspecs/features/moc.prf \
		/usr/local/qt5/mkspecs/features/unix/opengl.prf \
		/usr/local/qt5/mkspecs/features/uic.prf \
		/usr/local/qt5/mkspecs/features/unix/thread.prf \
		/usr/local/qt5/mkspecs/features/file_copies.prf \
		/usr/local/qt5/mkspecs/features/testcase_targets.prf \
		/usr/local/qt5/mkspecs/features/exceptions.prf \
		/usr/local/qt5/mkspecs/features/yacc.prf \
		/usr/local/qt5/mkspecs/features/lex.prf \
		canaveral.pro src/backend.h \
		src/buttons_tab.h \
		src/constants.h \
		src/frontend.h \
		src/pad.h \
		src/samples_tab.h \
		src/volume_tab.h \
		src/select_window.h \
		src/sample.h \
		src/wav_parser.h src/backend.cpp \
		src/buttons_tab.cpp \
		src/frontend.cpp \
		src/main.cpp \
		src/pad.cpp \
		src/samples_tab.cpp \
		src/volume_tab.cpp \
		src/select_window.cpp \
		src/sample.cpp \
		src/wav_parser.cpp
QMAKE_TARGET  = canaveral
DESTDIR       = bin/
TARGET        = bin/canaveral


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: canaveral.pro /usr/local/qt5/mkspecs/linux-g++/qmake.conf /usr/local/qt5/mkspecs/features/spec_pre.prf \
		/usr/local/qt5/mkspecs/common/unix.conf \
		/usr/local/qt5/mkspecs/common/linux.conf \
		/usr/local/qt5/mkspecs/common/sanitize.conf \
		/usr/local/qt5/mkspecs/common/gcc-base.conf \
		/usr/local/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/qt5/mkspecs/common/g++-base.conf \
		/usr/local/qt5/mkspecs/common/g++-unix.conf \
		/usr/local/qt5/mkspecs/qconfig.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/qt5/mkspecs/features/qt_functions.prf \
		/usr/local/qt5/mkspecs/features/qt_config.prf \
		/usr/local/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/local/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/local/qt5/mkspecs/features/default_pre.prf \
		/usr/local/qt5/mkspecs/features/resolve_config.prf \
		/usr/local/qt5/mkspecs/features/default_post.prf \
		/usr/local/qt5/mkspecs/features/warn_on.prf \
		/usr/local/qt5/mkspecs/features/qt.prf \
		/usr/local/qt5/mkspecs/features/resources.prf \
		/usr/local/qt5/mkspecs/features/moc.prf \
		/usr/local/qt5/mkspecs/features/unix/opengl.prf \
		/usr/local/qt5/mkspecs/features/uic.prf \
		/usr/local/qt5/mkspecs/features/unix/thread.prf \
		/usr/local/qt5/mkspecs/features/file_copies.prf \
		/usr/local/qt5/mkspecs/features/testcase_targets.prf \
		/usr/local/qt5/mkspecs/features/exceptions.prf \
		/usr/local/qt5/mkspecs/features/yacc.prf \
		/usr/local/qt5/mkspecs/features/lex.prf \
		canaveral.pro \
		/usr/local/qt5/lib/libQt5Widgets.prl \
		/usr/local/qt5/lib/libQt5Gui.prl \
		/usr/local/qt5/lib/libQt5Core.prl
	$(QMAKE) -o Makefile canaveral.pro
/usr/local/qt5/mkspecs/features/spec_pre.prf:
/usr/local/qt5/mkspecs/common/unix.conf:
/usr/local/qt5/mkspecs/common/linux.conf:
/usr/local/qt5/mkspecs/common/sanitize.conf:
/usr/local/qt5/mkspecs/common/gcc-base.conf:
/usr/local/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/local/qt5/mkspecs/common/g++-base.conf:
/usr/local/qt5/mkspecs/common/g++-unix.conf:
/usr/local/qt5/mkspecs/qconfig.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/qt5/mkspecs/features/qt_functions.prf:
/usr/local/qt5/mkspecs/features/qt_config.prf:
/usr/local/qt5/mkspecs/linux-g++/qmake.conf:
/usr/local/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/qt5/mkspecs/features/exclusive_builds.prf:
/usr/local/qt5/mkspecs/features/default_pre.prf:
/usr/local/qt5/mkspecs/features/resolve_config.prf:
/usr/local/qt5/mkspecs/features/default_post.prf:
/usr/local/qt5/mkspecs/features/warn_on.prf:
/usr/local/qt5/mkspecs/features/qt.prf:
/usr/local/qt5/mkspecs/features/resources.prf:
/usr/local/qt5/mkspecs/features/moc.prf:
/usr/local/qt5/mkspecs/features/unix/opengl.prf:
/usr/local/qt5/mkspecs/features/uic.prf:
/usr/local/qt5/mkspecs/features/unix/thread.prf:
/usr/local/qt5/mkspecs/features/file_copies.prf:
/usr/local/qt5/mkspecs/features/testcase_targets.prf:
/usr/local/qt5/mkspecs/features/exceptions.prf:
/usr/local/qt5/mkspecs/features/yacc.prf:
/usr/local/qt5/mkspecs/features/lex.prf:
canaveral.pro:
/usr/local/qt5/lib/libQt5Widgets.prl:
/usr/local/qt5/lib/libQt5Gui.prl:
/usr/local/qt5/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile canaveral.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/backend.h src/buttons_tab.h src/constants.h src/frontend.h src/pad.h src/samples_tab.h src/volume_tab.h src/select_window.h src/sample.h src/wav_parser.h $(DISTDIR)/
	$(COPY_FILE) --parents src/backend.cpp src/buttons_tab.cpp src/frontend.cpp src/main.cpp src/pad.cpp src/samples_tab.cpp src/volume_tab.cpp src/select_window.cpp src/sample.cpp src/wav_parser.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: .moc/moc_pad.cpp .moc/moc_samples_tab.cpp .moc/moc_select_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) .moc/moc_pad.cpp .moc/moc_samples_tab.cpp .moc/moc_select_window.cpp
.moc/moc_pad.cpp: /usr/local/qt5/include/QtWidgets/QPushButton \
		/usr/local/qt5/include/QtWidgets/qpushbutton.h \
		/usr/local/qt5/include/QtWidgets/qabstractbutton.h \
		/usr/local/qt5/include/QtGui/qicon.h \
		/usr/local/qt5/include/QtCore/qglobal.h \
		/usr/local/qt5/include/QtCore/qconfig.h \
		/usr/local/qt5/include/QtCore/qfeatures.h \
		/usr/local/qt5/include/QtCore/qsystemdetection.h \
		/usr/local/qt5/include/QtCore/qprocessordetection.h \
		/usr/local/qt5/include/QtCore/qcompilerdetection.h \
		/usr/local/qt5/include/QtCore/qtypeinfo.h \
		/usr/local/qt5/include/QtCore/qtypetraits.h \
		/usr/local/qt5/include/QtCore/qisenum.h \
		/usr/local/qt5/include/QtCore/qsysinfo.h \
		/usr/local/qt5/include/QtCore/qlogging.h \
		/usr/local/qt5/include/QtCore/qflags.h \
		/usr/local/qt5/include/QtCore/qatomic.h \
		/usr/local/qt5/include/QtCore/qbasicatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt5/include/QtCore/qgenericatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt5/include/QtCore/qatomic_msvc.h \
		/usr/local/qt5/include/QtCore/qglobalstatic.h \
		/usr/local/qt5/include/QtCore/qmutex.h \
		/usr/local/qt5/include/QtCore/qnumeric.h \
		/usr/local/qt5/include/QtCore/qversiontagging.h \
		/usr/local/qt5/include/QtCore/qsize.h \
		/usr/local/qt5/include/QtCore/qnamespace.h \
		/usr/local/qt5/include/QtCore/qlist.h \
		/usr/local/qt5/include/QtCore/qalgorithms.h \
		/usr/local/qt5/include/QtCore/qiterator.h \
		/usr/local/qt5/include/QtCore/qrefcount.h \
		/usr/local/qt5/include/QtCore/qarraydata.h \
		/usr/local/qt5/include/QtCore/qhashfunctions.h \
		/usr/local/qt5/include/QtCore/qchar.h \
		/usr/local/qt5/include/QtCore/qpair.h \
		/usr/local/qt5/include/QtCore/qbytearraylist.h \
		/usr/local/qt5/include/QtCore/qbytearray.h \
		/usr/local/qt5/include/QtCore/qstring.h \
		/usr/local/qt5/include/QtCore/qstringbuilder.h \
		/usr/local/qt5/include/QtCore/qstringlist.h \
		/usr/local/qt5/include/QtCore/qregexp.h \
		/usr/local/qt5/include/QtCore/qstringmatcher.h \
		/usr/local/qt5/include/QtGui/qpixmap.h \
		/usr/local/qt5/include/QtGui/qpaintdevice.h \
		/usr/local/qt5/include/QtGui/qwindowdefs.h \
		/usr/local/qt5/include/QtCore/qobjectdefs.h \
		/usr/local/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt5/include/QtGui/qwindowdefs_win.h \
		/usr/local/qt5/include/QtCore/qrect.h \
		/usr/local/qt5/include/QtCore/qmargins.h \
		/usr/local/qt5/include/QtCore/qpoint.h \
		/usr/local/qt5/include/QtGui/qcolor.h \
		/usr/local/qt5/include/QtGui/qrgb.h \
		/usr/local/qt5/include/QtGui/qrgba64.h \
		/usr/local/qt5/include/QtCore/qsharedpointer.h \
		/usr/local/qt5/include/QtCore/qshareddata.h \
		/usr/local/qt5/include/QtCore/qhash.h \
		/usr/local/qt5/include/QtCore/qsharedpointer_impl.h \
		/usr/local/qt5/include/QtCore/qobject.h \
		/usr/local/qt5/include/QtCore/qcoreevent.h \
		/usr/local/qt5/include/QtCore/qscopedpointer.h \
		/usr/local/qt5/include/QtCore/qmetatype.h \
		/usr/local/qt5/include/QtCore/qvarlengtharray.h \
		/usr/local/qt5/include/QtCore/qcontainerfwd.h \
		/usr/local/qt5/include/QtCore/qobject_impl.h \
		/usr/local/qt5/include/QtGui/qimage.h \
		/usr/local/qt5/include/QtGui/qpixelformat.h \
		/usr/local/qt5/include/QtGui/qtransform.h \
		/usr/local/qt5/include/QtGui/qmatrix.h \
		/usr/local/qt5/include/QtGui/qpolygon.h \
		/usr/local/qt5/include/QtCore/qvector.h \
		/usr/local/qt5/include/QtGui/qregion.h \
		/usr/local/qt5/include/QtCore/qdatastream.h \
		/usr/local/qt5/include/QtCore/qiodevice.h \
		/usr/local/qt5/include/QtCore/qline.h \
		/usr/local/qt5/include/QtGui/qpainterpath.h \
		/usr/local/qt5/include/QtGui/qkeysequence.h \
		/usr/local/qt5/include/QtWidgets/qwidget.h \
		/usr/local/qt5/include/QtGui/qpalette.h \
		/usr/local/qt5/include/QtGui/qbrush.h \
		/usr/local/qt5/include/QtGui/qfont.h \
		/usr/local/qt5/include/QtGui/qfontmetrics.h \
		/usr/local/qt5/include/QtGui/qfontinfo.h \
		/usr/local/qt5/include/QtWidgets/qsizepolicy.h \
		/usr/local/qt5/include/QtGui/qcursor.h \
		/usr/local/qt5/include/QtGui/qevent.h \
		/usr/local/qt5/include/QtCore/qvariant.h \
		/usr/local/qt5/include/QtCore/qmap.h \
		/usr/local/qt5/include/QtCore/qdebug.h \
		/usr/local/qt5/include/QtCore/qtextstream.h \
		/usr/local/qt5/include/QtCore/qlocale.h \
		/usr/local/qt5/include/QtCore/qset.h \
		/usr/local/qt5/include/QtCore/qcontiguouscache.h \
		/usr/local/qt5/include/QtCore/qurl.h \
		/usr/local/qt5/include/QtCore/qurlquery.h \
		/usr/local/qt5/include/QtCore/qfile.h \
		/usr/local/qt5/include/QtCore/qfiledevice.h \
		/usr/local/qt5/include/QtGui/qvector2d.h \
		/usr/local/qt5/include/QtGui/qtouchdevice.h \
		/usr/local/qt5/include/QtWidgets/QSlider \
		/usr/local/qt5/include/QtWidgets/qslider.h \
		/usr/local/qt5/include/QtWidgets/qabstractslider.h \
		/usr/local/qt5/include/QtWidgets/QWidget \
		src/backend.h \
		src/sample.h \
		/usr/local/qt5/include/QtCore/QString \
		/usr/local/qt5/include/QtCore/QByteArray \
		src/pad.h \
		/usr/local/qt5/bin/moc
	/usr/local/qt5/bin/moc $(DEFINES) -I/usr/local/qt5/mkspecs/linux-g++ -I/home/victor/Documents/canaveral -I/home/victor/Documents/canaveral -I/usr/local/qt5/include -I/usr/local/qt5/include/QtWidgets -I/usr/local/qt5/include/QtGui -I/usr/local/qt5/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/pad.h -o .moc/moc_pad.cpp

.moc/moc_samples_tab.cpp: /usr/local/qt5/include/QtWidgets/QWidget \
		/usr/local/qt5/include/QtWidgets/qwidget.h \
		/usr/local/qt5/include/QtGui/qwindowdefs.h \
		/usr/local/qt5/include/QtCore/qglobal.h \
		/usr/local/qt5/include/QtCore/qconfig.h \
		/usr/local/qt5/include/QtCore/qfeatures.h \
		/usr/local/qt5/include/QtCore/qsystemdetection.h \
		/usr/local/qt5/include/QtCore/qprocessordetection.h \
		/usr/local/qt5/include/QtCore/qcompilerdetection.h \
		/usr/local/qt5/include/QtCore/qtypeinfo.h \
		/usr/local/qt5/include/QtCore/qtypetraits.h \
		/usr/local/qt5/include/QtCore/qisenum.h \
		/usr/local/qt5/include/QtCore/qsysinfo.h \
		/usr/local/qt5/include/QtCore/qlogging.h \
		/usr/local/qt5/include/QtCore/qflags.h \
		/usr/local/qt5/include/QtCore/qatomic.h \
		/usr/local/qt5/include/QtCore/qbasicatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt5/include/QtCore/qgenericatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt5/include/QtCore/qatomic_msvc.h \
		/usr/local/qt5/include/QtCore/qglobalstatic.h \
		/usr/local/qt5/include/QtCore/qmutex.h \
		/usr/local/qt5/include/QtCore/qnumeric.h \
		/usr/local/qt5/include/QtCore/qversiontagging.h \
		/usr/local/qt5/include/QtCore/qobjectdefs.h \
		/usr/local/qt5/include/QtCore/qnamespace.h \
		/usr/local/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt5/include/QtGui/qwindowdefs_win.h \
		/usr/local/qt5/include/QtCore/qobject.h \
		/usr/local/qt5/include/QtCore/qstring.h \
		/usr/local/qt5/include/QtCore/qchar.h \
		/usr/local/qt5/include/QtCore/qbytearray.h \
		/usr/local/qt5/include/QtCore/qrefcount.h \
		/usr/local/qt5/include/QtCore/qarraydata.h \
		/usr/local/qt5/include/QtCore/qstringbuilder.h \
		/usr/local/qt5/include/QtCore/qlist.h \
		/usr/local/qt5/include/QtCore/qalgorithms.h \
		/usr/local/qt5/include/QtCore/qiterator.h \
		/usr/local/qt5/include/QtCore/qhashfunctions.h \
		/usr/local/qt5/include/QtCore/qpair.h \
		/usr/local/qt5/include/QtCore/qbytearraylist.h \
		/usr/local/qt5/include/QtCore/qstringlist.h \
		/usr/local/qt5/include/QtCore/qregexp.h \
		/usr/local/qt5/include/QtCore/qstringmatcher.h \
		/usr/local/qt5/include/QtCore/qcoreevent.h \
		/usr/local/qt5/include/QtCore/qscopedpointer.h \
		/usr/local/qt5/include/QtCore/qmetatype.h \
		/usr/local/qt5/include/QtCore/qvarlengtharray.h \
		/usr/local/qt5/include/QtCore/qcontainerfwd.h \
		/usr/local/qt5/include/QtCore/qobject_impl.h \
		/usr/local/qt5/include/QtCore/qmargins.h \
		/usr/local/qt5/include/QtGui/qpaintdevice.h \
		/usr/local/qt5/include/QtCore/qrect.h \
		/usr/local/qt5/include/QtCore/qsize.h \
		/usr/local/qt5/include/QtCore/qpoint.h \
		/usr/local/qt5/include/QtGui/qpalette.h \
		/usr/local/qt5/include/QtGui/qcolor.h \
		/usr/local/qt5/include/QtGui/qrgb.h \
		/usr/local/qt5/include/QtGui/qrgba64.h \
		/usr/local/qt5/include/QtGui/qbrush.h \
		/usr/local/qt5/include/QtCore/qvector.h \
		/usr/local/qt5/include/QtGui/qmatrix.h \
		/usr/local/qt5/include/QtGui/qpolygon.h \
		/usr/local/qt5/include/QtGui/qregion.h \
		/usr/local/qt5/include/QtCore/qdatastream.h \
		/usr/local/qt5/include/QtCore/qiodevice.h \
		/usr/local/qt5/include/QtCore/qline.h \
		/usr/local/qt5/include/QtGui/qtransform.h \
		/usr/local/qt5/include/QtGui/qpainterpath.h \
		/usr/local/qt5/include/QtGui/qimage.h \
		/usr/local/qt5/include/QtGui/qpixelformat.h \
		/usr/local/qt5/include/QtGui/qpixmap.h \
		/usr/local/qt5/include/QtCore/qsharedpointer.h \
		/usr/local/qt5/include/QtCore/qshareddata.h \
		/usr/local/qt5/include/QtCore/qhash.h \
		/usr/local/qt5/include/QtCore/qsharedpointer_impl.h \
		/usr/local/qt5/include/QtGui/qfont.h \
		/usr/local/qt5/include/QtGui/qfontmetrics.h \
		/usr/local/qt5/include/QtGui/qfontinfo.h \
		/usr/local/qt5/include/QtWidgets/qsizepolicy.h \
		/usr/local/qt5/include/QtGui/qcursor.h \
		/usr/local/qt5/include/QtGui/qkeysequence.h \
		/usr/local/qt5/include/QtGui/qevent.h \
		/usr/local/qt5/include/QtCore/qvariant.h \
		/usr/local/qt5/include/QtCore/qmap.h \
		/usr/local/qt5/include/QtCore/qdebug.h \
		/usr/local/qt5/include/QtCore/qtextstream.h \
		/usr/local/qt5/include/QtCore/qlocale.h \
		/usr/local/qt5/include/QtCore/qset.h \
		/usr/local/qt5/include/QtCore/qcontiguouscache.h \
		/usr/local/qt5/include/QtCore/qurl.h \
		/usr/local/qt5/include/QtCore/qurlquery.h \
		/usr/local/qt5/include/QtCore/qfile.h \
		/usr/local/qt5/include/QtCore/qfiledevice.h \
		/usr/local/qt5/include/QtGui/qvector2d.h \
		/usr/local/qt5/include/QtGui/qtouchdevice.h \
		/usr/local/qt5/include/QtWidgets/QListWidget \
		/usr/local/qt5/include/QtWidgets/qlistwidget.h \
		/usr/local/qt5/include/QtWidgets/qlistview.h \
		/usr/local/qt5/include/QtWidgets/qabstractitemview.h \
		/usr/local/qt5/include/QtWidgets/qabstractscrollarea.h \
		/usr/local/qt5/include/QtWidgets/qframe.h \
		/usr/local/qt5/include/QtCore/qabstractitemmodel.h \
		/usr/local/qt5/include/QtCore/qitemselectionmodel.h \
		/usr/local/qt5/include/QtWidgets/qabstractitemdelegate.h \
		/usr/local/qt5/include/QtWidgets/qstyleoption.h \
		/usr/local/qt5/include/QtWidgets/qabstractspinbox.h \
		/usr/local/qt5/include/QtGui/qvalidator.h \
		/usr/local/qt5/include/QtCore/qregularexpression.h \
		/usr/local/qt5/include/QtGui/qicon.h \
		/usr/local/qt5/include/QtWidgets/qslider.h \
		/usr/local/qt5/include/QtWidgets/qabstractslider.h \
		/usr/local/qt5/include/QtWidgets/qstyle.h \
		/usr/local/qt5/include/QtWidgets/qtabbar.h \
		/usr/local/qt5/include/QtWidgets/qtabwidget.h \
		/usr/local/qt5/include/QtWidgets/qrubberband.h \
		/usr/local/qt5/include/QtWidgets/QPushButton \
		/usr/local/qt5/include/QtWidgets/qpushbutton.h \
		/usr/local/qt5/include/QtWidgets/qabstractbutton.h \
		/usr/local/qt5/include/QtCore/QVector \
		src/pad.h \
		/usr/local/qt5/include/QtWidgets/QSlider \
		src/backend.h \
		src/sample.h \
		/usr/local/qt5/include/QtCore/QString \
		/usr/local/qt5/include/QtCore/QByteArray \
		src/samples_tab.h \
		/usr/local/qt5/bin/moc
	/usr/local/qt5/bin/moc $(DEFINES) -I/usr/local/qt5/mkspecs/linux-g++ -I/home/victor/Documents/canaveral -I/home/victor/Documents/canaveral -I/usr/local/qt5/include -I/usr/local/qt5/include/QtWidgets -I/usr/local/qt5/include/QtGui -I/usr/local/qt5/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/samples_tab.h -o .moc/moc_samples_tab.cpp

.moc/moc_select_window.cpp: /usr/local/qt5/include/QtWidgets/QWidget \
		/usr/local/qt5/include/QtWidgets/qwidget.h \
		/usr/local/qt5/include/QtGui/qwindowdefs.h \
		/usr/local/qt5/include/QtCore/qglobal.h \
		/usr/local/qt5/include/QtCore/qconfig.h \
		/usr/local/qt5/include/QtCore/qfeatures.h \
		/usr/local/qt5/include/QtCore/qsystemdetection.h \
		/usr/local/qt5/include/QtCore/qprocessordetection.h \
		/usr/local/qt5/include/QtCore/qcompilerdetection.h \
		/usr/local/qt5/include/QtCore/qtypeinfo.h \
		/usr/local/qt5/include/QtCore/qtypetraits.h \
		/usr/local/qt5/include/QtCore/qisenum.h \
		/usr/local/qt5/include/QtCore/qsysinfo.h \
		/usr/local/qt5/include/QtCore/qlogging.h \
		/usr/local/qt5/include/QtCore/qflags.h \
		/usr/local/qt5/include/QtCore/qatomic.h \
		/usr/local/qt5/include/QtCore/qbasicatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt5/include/QtCore/qgenericatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt5/include/QtCore/qatomic_msvc.h \
		/usr/local/qt5/include/QtCore/qglobalstatic.h \
		/usr/local/qt5/include/QtCore/qmutex.h \
		/usr/local/qt5/include/QtCore/qnumeric.h \
		/usr/local/qt5/include/QtCore/qversiontagging.h \
		/usr/local/qt5/include/QtCore/qobjectdefs.h \
		/usr/local/qt5/include/QtCore/qnamespace.h \
		/usr/local/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt5/include/QtGui/qwindowdefs_win.h \
		/usr/local/qt5/include/QtCore/qobject.h \
		/usr/local/qt5/include/QtCore/qstring.h \
		/usr/local/qt5/include/QtCore/qchar.h \
		/usr/local/qt5/include/QtCore/qbytearray.h \
		/usr/local/qt5/include/QtCore/qrefcount.h \
		/usr/local/qt5/include/QtCore/qarraydata.h \
		/usr/local/qt5/include/QtCore/qstringbuilder.h \
		/usr/local/qt5/include/QtCore/qlist.h \
		/usr/local/qt5/include/QtCore/qalgorithms.h \
		/usr/local/qt5/include/QtCore/qiterator.h \
		/usr/local/qt5/include/QtCore/qhashfunctions.h \
		/usr/local/qt5/include/QtCore/qpair.h \
		/usr/local/qt5/include/QtCore/qbytearraylist.h \
		/usr/local/qt5/include/QtCore/qstringlist.h \
		/usr/local/qt5/include/QtCore/qregexp.h \
		/usr/local/qt5/include/QtCore/qstringmatcher.h \
		/usr/local/qt5/include/QtCore/qcoreevent.h \
		/usr/local/qt5/include/QtCore/qscopedpointer.h \
		/usr/local/qt5/include/QtCore/qmetatype.h \
		/usr/local/qt5/include/QtCore/qvarlengtharray.h \
		/usr/local/qt5/include/QtCore/qcontainerfwd.h \
		/usr/local/qt5/include/QtCore/qobject_impl.h \
		/usr/local/qt5/include/QtCore/qmargins.h \
		/usr/local/qt5/include/QtGui/qpaintdevice.h \
		/usr/local/qt5/include/QtCore/qrect.h \
		/usr/local/qt5/include/QtCore/qsize.h \
		/usr/local/qt5/include/QtCore/qpoint.h \
		/usr/local/qt5/include/QtGui/qpalette.h \
		/usr/local/qt5/include/QtGui/qcolor.h \
		/usr/local/qt5/include/QtGui/qrgb.h \
		/usr/local/qt5/include/QtGui/qrgba64.h \
		/usr/local/qt5/include/QtGui/qbrush.h \
		/usr/local/qt5/include/QtCore/qvector.h \
		/usr/local/qt5/include/QtGui/qmatrix.h \
		/usr/local/qt5/include/QtGui/qpolygon.h \
		/usr/local/qt5/include/QtGui/qregion.h \
		/usr/local/qt5/include/QtCore/qdatastream.h \
		/usr/local/qt5/include/QtCore/qiodevice.h \
		/usr/local/qt5/include/QtCore/qline.h \
		/usr/local/qt5/include/QtGui/qtransform.h \
		/usr/local/qt5/include/QtGui/qpainterpath.h \
		/usr/local/qt5/include/QtGui/qimage.h \
		/usr/local/qt5/include/QtGui/qpixelformat.h \
		/usr/local/qt5/include/QtGui/qpixmap.h \
		/usr/local/qt5/include/QtCore/qsharedpointer.h \
		/usr/local/qt5/include/QtCore/qshareddata.h \
		/usr/local/qt5/include/QtCore/qhash.h \
		/usr/local/qt5/include/QtCore/qsharedpointer_impl.h \
		/usr/local/qt5/include/QtGui/qfont.h \
		/usr/local/qt5/include/QtGui/qfontmetrics.h \
		/usr/local/qt5/include/QtGui/qfontinfo.h \
		/usr/local/qt5/include/QtWidgets/qsizepolicy.h \
		/usr/local/qt5/include/QtGui/qcursor.h \
		/usr/local/qt5/include/QtGui/qkeysequence.h \
		/usr/local/qt5/include/QtGui/qevent.h \
		/usr/local/qt5/include/QtCore/qvariant.h \
		/usr/local/qt5/include/QtCore/qmap.h \
		/usr/local/qt5/include/QtCore/qdebug.h \
		/usr/local/qt5/include/QtCore/qtextstream.h \
		/usr/local/qt5/include/QtCore/qlocale.h \
		/usr/local/qt5/include/QtCore/qset.h \
		/usr/local/qt5/include/QtCore/qcontiguouscache.h \
		/usr/local/qt5/include/QtCore/qurl.h \
		/usr/local/qt5/include/QtCore/qurlquery.h \
		/usr/local/qt5/include/QtCore/qfile.h \
		/usr/local/qt5/include/QtCore/qfiledevice.h \
		/usr/local/qt5/include/QtGui/qvector2d.h \
		/usr/local/qt5/include/QtGui/qtouchdevice.h \
		/usr/local/qt5/include/QtWidgets/QPushButton \
		/usr/local/qt5/include/QtWidgets/qpushbutton.h \
		/usr/local/qt5/include/QtWidgets/qabstractbutton.h \
		/usr/local/qt5/include/QtGui/qicon.h \
		/usr/local/qt5/include/QtWidgets/QListWidget \
		/usr/local/qt5/include/QtWidgets/qlistwidget.h \
		/usr/local/qt5/include/QtWidgets/qlistview.h \
		/usr/local/qt5/include/QtWidgets/qabstractitemview.h \
		/usr/local/qt5/include/QtWidgets/qabstractscrollarea.h \
		/usr/local/qt5/include/QtWidgets/qframe.h \
		/usr/local/qt5/include/QtCore/qabstractitemmodel.h \
		/usr/local/qt5/include/QtCore/qitemselectionmodel.h \
		/usr/local/qt5/include/QtWidgets/qabstractitemdelegate.h \
		/usr/local/qt5/include/QtWidgets/qstyleoption.h \
		/usr/local/qt5/include/QtWidgets/qabstractspinbox.h \
		/usr/local/qt5/include/QtGui/qvalidator.h \
		/usr/local/qt5/include/QtCore/qregularexpression.h \
		/usr/local/qt5/include/QtWidgets/qslider.h \
		/usr/local/qt5/include/QtWidgets/qabstractslider.h \
		/usr/local/qt5/include/QtWidgets/qstyle.h \
		/usr/local/qt5/include/QtWidgets/qtabbar.h \
		/usr/local/qt5/include/QtWidgets/qtabwidget.h \
		/usr/local/qt5/include/QtWidgets/qrubberband.h \
		/usr/local/qt5/include/QtWidgets/QLineEdit \
		/usr/local/qt5/include/QtWidgets/qlineedit.h \
		/usr/local/qt5/include/QtGui/qtextcursor.h \
		/usr/local/qt5/include/QtGui/qtextformat.h \
		/usr/local/qt5/include/QtGui/qpen.h \
		/usr/local/qt5/include/QtGui/qtextoption.h \
		/usr/local/qt5/include/QtCore/QString \
		src/samples_tab.h \
		/usr/local/qt5/include/QtCore/QVector \
		src/pad.h \
		/usr/local/qt5/include/QtWidgets/QSlider \
		src/backend.h \
		src/sample.h \
		/usr/local/qt5/include/QtCore/QByteArray \
		src/select_window.h \
		/usr/local/qt5/bin/moc
	/usr/local/qt5/bin/moc $(DEFINES) -I/usr/local/qt5/mkspecs/linux-g++ -I/home/victor/Documents/canaveral -I/home/victor/Documents/canaveral -I/usr/local/qt5/include -I/usr/local/qt5/include/QtWidgets -I/usr/local/qt5/include/QtGui -I/usr/local/qt5/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/select_window.h -o .moc/moc_select_window.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

.obj/backend.o: src/backend.cpp src/backend.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/backend.o src/backend.cpp

.obj/buttons_tab.o: src/buttons_tab.cpp /usr/local/qt5/include/QtWidgets/QGridLayout \
		/usr/local/qt5/include/QtWidgets/qgridlayout.h \
		/usr/local/qt5/include/QtWidgets/qlayout.h \
		/usr/local/qt5/include/QtCore/qobject.h \
		/usr/local/qt5/include/QtCore/qobjectdefs.h \
		/usr/local/qt5/include/QtCore/qnamespace.h \
		/usr/local/qt5/include/QtCore/qglobal.h \
		/usr/local/qt5/include/QtCore/qconfig.h \
		/usr/local/qt5/include/QtCore/qfeatures.h \
		/usr/local/qt5/include/QtCore/qsystemdetection.h \
		/usr/local/qt5/include/QtCore/qprocessordetection.h \
		/usr/local/qt5/include/QtCore/qcompilerdetection.h \
		/usr/local/qt5/include/QtCore/qtypeinfo.h \
		/usr/local/qt5/include/QtCore/qtypetraits.h \
		/usr/local/qt5/include/QtCore/qisenum.h \
		/usr/local/qt5/include/QtCore/qsysinfo.h \
		/usr/local/qt5/include/QtCore/qlogging.h \
		/usr/local/qt5/include/QtCore/qflags.h \
		/usr/local/qt5/include/QtCore/qatomic.h \
		/usr/local/qt5/include/QtCore/qbasicatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt5/include/QtCore/qgenericatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt5/include/QtCore/qatomic_msvc.h \
		/usr/local/qt5/include/QtCore/qglobalstatic.h \
		/usr/local/qt5/include/QtCore/qmutex.h \
		/usr/local/qt5/include/QtCore/qnumeric.h \
		/usr/local/qt5/include/QtCore/qversiontagging.h \
		/usr/local/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt5/include/QtCore/qstring.h \
		/usr/local/qt5/include/QtCore/qchar.h \
		/usr/local/qt5/include/QtCore/qbytearray.h \
		/usr/local/qt5/include/QtCore/qrefcount.h \
		/usr/local/qt5/include/QtCore/qarraydata.h \
		/usr/local/qt5/include/QtCore/qstringbuilder.h \
		/usr/local/qt5/include/QtCore/qlist.h \
		/usr/local/qt5/include/QtCore/qalgorithms.h \
		/usr/local/qt5/include/QtCore/qiterator.h \
		/usr/local/qt5/include/QtCore/qhashfunctions.h \
		/usr/local/qt5/include/QtCore/qpair.h \
		/usr/local/qt5/include/QtCore/qbytearraylist.h \
		/usr/local/qt5/include/QtCore/qstringlist.h \
		/usr/local/qt5/include/QtCore/qregexp.h \
		/usr/local/qt5/include/QtCore/qstringmatcher.h \
		/usr/local/qt5/include/QtCore/qcoreevent.h \
		/usr/local/qt5/include/QtCore/qscopedpointer.h \
		/usr/local/qt5/include/QtCore/qmetatype.h \
		/usr/local/qt5/include/QtCore/qvarlengtharray.h \
		/usr/local/qt5/include/QtCore/qcontainerfwd.h \
		/usr/local/qt5/include/QtCore/qobject_impl.h \
		/usr/local/qt5/include/QtWidgets/qlayoutitem.h \
		/usr/local/qt5/include/QtWidgets/qsizepolicy.h \
		/usr/local/qt5/include/QtCore/qrect.h \
		/usr/local/qt5/include/QtCore/qmargins.h \
		/usr/local/qt5/include/QtCore/qsize.h \
		/usr/local/qt5/include/QtCore/qpoint.h \
		/usr/local/qt5/include/QtWidgets/qboxlayout.h \
		/usr/local/qt5/include/QtWidgets/qwidget.h \
		/usr/local/qt5/include/QtGui/qwindowdefs.h \
		/usr/local/qt5/include/QtGui/qwindowdefs_win.h \
		/usr/local/qt5/include/QtGui/qpaintdevice.h \
		/usr/local/qt5/include/QtGui/qpalette.h \
		/usr/local/qt5/include/QtGui/qcolor.h \
		/usr/local/qt5/include/QtGui/qrgb.h \
		/usr/local/qt5/include/QtGui/qrgba64.h \
		/usr/local/qt5/include/QtGui/qbrush.h \
		/usr/local/qt5/include/QtCore/qvector.h \
		/usr/local/qt5/include/QtGui/qmatrix.h \
		/usr/local/qt5/include/QtGui/qpolygon.h \
		/usr/local/qt5/include/QtGui/qregion.h \
		/usr/local/qt5/include/QtCore/qdatastream.h \
		/usr/local/qt5/include/QtCore/qiodevice.h \
		/usr/local/qt5/include/QtCore/qline.h \
		/usr/local/qt5/include/QtGui/qtransform.h \
		/usr/local/qt5/include/QtGui/qpainterpath.h \
		/usr/local/qt5/include/QtGui/qimage.h \
		/usr/local/qt5/include/QtGui/qpixelformat.h \
		/usr/local/qt5/include/QtGui/qpixmap.h \
		/usr/local/qt5/include/QtCore/qsharedpointer.h \
		/usr/local/qt5/include/QtCore/qshareddata.h \
		/usr/local/qt5/include/QtCore/qhash.h \
		/usr/local/qt5/include/QtCore/qsharedpointer_impl.h \
		/usr/local/qt5/include/QtGui/qfont.h \
		/usr/local/qt5/include/QtGui/qfontmetrics.h \
		/usr/local/qt5/include/QtGui/qfontinfo.h \
		/usr/local/qt5/include/QtGui/qcursor.h \
		/usr/local/qt5/include/QtGui/qkeysequence.h \
		/usr/local/qt5/include/QtGui/qevent.h \
		/usr/local/qt5/include/QtCore/qvariant.h \
		/usr/local/qt5/include/QtCore/qmap.h \
		/usr/local/qt5/include/QtCore/qdebug.h \
		/usr/local/qt5/include/QtCore/qtextstream.h \
		/usr/local/qt5/include/QtCore/qlocale.h \
		/usr/local/qt5/include/QtCore/qset.h \
		/usr/local/qt5/include/QtCore/qcontiguouscache.h \
		/usr/local/qt5/include/QtCore/qurl.h \
		/usr/local/qt5/include/QtCore/qurlquery.h \
		/usr/local/qt5/include/QtCore/qfile.h \
		/usr/local/qt5/include/QtCore/qfiledevice.h \
		/usr/local/qt5/include/QtGui/qvector2d.h \
		/usr/local/qt5/include/QtGui/qtouchdevice.h \
		/usr/local/qt5/include/QtWidgets/QPushButton \
		/usr/local/qt5/include/QtWidgets/qpushbutton.h \
		/usr/local/qt5/include/QtWidgets/qabstractbutton.h \
		/usr/local/qt5/include/QtGui/qicon.h \
		/usr/local/qt5/include/QtCore/QVector \
		src/buttons_tab.h \
		/usr/local/qt5/include/QtWidgets/QWidget \
		src/pad.h \
		/usr/local/qt5/include/QtWidgets/QSlider \
		/usr/local/qt5/include/QtWidgets/qslider.h \
		/usr/local/qt5/include/QtWidgets/qabstractslider.h \
		src/backend.h \
		src/sample.h \
		/usr/local/qt5/include/QtCore/QString \
		/usr/local/qt5/include/QtCore/QByteArray \
		src/constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/buttons_tab.o src/buttons_tab.cpp

.obj/frontend.o: src/frontend.cpp /usr/local/qt5/include/QtWidgets/QVBoxLayout \
		/usr/local/qt5/include/QtWidgets/qboxlayout.h \
		/usr/local/qt5/include/QtWidgets/qlayout.h \
		/usr/local/qt5/include/QtCore/qobject.h \
		/usr/local/qt5/include/QtCore/qobjectdefs.h \
		/usr/local/qt5/include/QtCore/qnamespace.h \
		/usr/local/qt5/include/QtCore/qglobal.h \
		/usr/local/qt5/include/QtCore/qconfig.h \
		/usr/local/qt5/include/QtCore/qfeatures.h \
		/usr/local/qt5/include/QtCore/qsystemdetection.h \
		/usr/local/qt5/include/QtCore/qprocessordetection.h \
		/usr/local/qt5/include/QtCore/qcompilerdetection.h \
		/usr/local/qt5/include/QtCore/qtypeinfo.h \
		/usr/local/qt5/include/QtCore/qtypetraits.h \
		/usr/local/qt5/include/QtCore/qisenum.h \
		/usr/local/qt5/include/QtCore/qsysinfo.h \
		/usr/local/qt5/include/QtCore/qlogging.h \
		/usr/local/qt5/include/QtCore/qflags.h \
		/usr/local/qt5/include/QtCore/qatomic.h \
		/usr/local/qt5/include/QtCore/qbasicatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt5/include/QtCore/qgenericatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt5/include/QtCore/qatomic_msvc.h \
		/usr/local/qt5/include/QtCore/qglobalstatic.h \
		/usr/local/qt5/include/QtCore/qmutex.h \
		/usr/local/qt5/include/QtCore/qnumeric.h \
		/usr/local/qt5/include/QtCore/qversiontagging.h \
		/usr/local/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt5/include/QtCore/qstring.h \
		/usr/local/qt5/include/QtCore/qchar.h \
		/usr/local/qt5/include/QtCore/qbytearray.h \
		/usr/local/qt5/include/QtCore/qrefcount.h \
		/usr/local/qt5/include/QtCore/qarraydata.h \
		/usr/local/qt5/include/QtCore/qstringbuilder.h \
		/usr/local/qt5/include/QtCore/qlist.h \
		/usr/local/qt5/include/QtCore/qalgorithms.h \
		/usr/local/qt5/include/QtCore/qiterator.h \
		/usr/local/qt5/include/QtCore/qhashfunctions.h \
		/usr/local/qt5/include/QtCore/qpair.h \
		/usr/local/qt5/include/QtCore/qbytearraylist.h \
		/usr/local/qt5/include/QtCore/qstringlist.h \
		/usr/local/qt5/include/QtCore/qregexp.h \
		/usr/local/qt5/include/QtCore/qstringmatcher.h \
		/usr/local/qt5/include/QtCore/qcoreevent.h \
		/usr/local/qt5/include/QtCore/qscopedpointer.h \
		/usr/local/qt5/include/QtCore/qmetatype.h \
		/usr/local/qt5/include/QtCore/qvarlengtharray.h \
		/usr/local/qt5/include/QtCore/qcontainerfwd.h \
		/usr/local/qt5/include/QtCore/qobject_impl.h \
		/usr/local/qt5/include/QtWidgets/qlayoutitem.h \
		/usr/local/qt5/include/QtWidgets/qsizepolicy.h \
		/usr/local/qt5/include/QtCore/qrect.h \
		/usr/local/qt5/include/QtCore/qmargins.h \
		/usr/local/qt5/include/QtCore/qsize.h \
		/usr/local/qt5/include/QtCore/qpoint.h \
		/usr/local/qt5/include/QtWidgets/qgridlayout.h \
		/usr/local/qt5/include/QtWidgets/qwidget.h \
		/usr/local/qt5/include/QtGui/qwindowdefs.h \
		/usr/local/qt5/include/QtGui/qwindowdefs_win.h \
		/usr/local/qt5/include/QtGui/qpaintdevice.h \
		/usr/local/qt5/include/QtGui/qpalette.h \
		/usr/local/qt5/include/QtGui/qcolor.h \
		/usr/local/qt5/include/QtGui/qrgb.h \
		/usr/local/qt5/include/QtGui/qrgba64.h \
		/usr/local/qt5/include/QtGui/qbrush.h \
		/usr/local/qt5/include/QtCore/qvector.h \
		/usr/local/qt5/include/QtGui/qmatrix.h \
		/usr/local/qt5/include/QtGui/qpolygon.h \
		/usr/local/qt5/include/QtGui/qregion.h \
		/usr/local/qt5/include/QtCore/qdatastream.h \
		/usr/local/qt5/include/QtCore/qiodevice.h \
		/usr/local/qt5/include/QtCore/qline.h \
		/usr/local/qt5/include/QtGui/qtransform.h \
		/usr/local/qt5/include/QtGui/qpainterpath.h \
		/usr/local/qt5/include/QtGui/qimage.h \
		/usr/local/qt5/include/QtGui/qpixelformat.h \
		/usr/local/qt5/include/QtGui/qpixmap.h \
		/usr/local/qt5/include/QtCore/qsharedpointer.h \
		/usr/local/qt5/include/QtCore/qshareddata.h \
		/usr/local/qt5/include/QtCore/qhash.h \
		/usr/local/qt5/include/QtCore/qsharedpointer_impl.h \
		/usr/local/qt5/include/QtGui/qfont.h \
		/usr/local/qt5/include/QtGui/qfontmetrics.h \
		/usr/local/qt5/include/QtGui/qfontinfo.h \
		/usr/local/qt5/include/QtGui/qcursor.h \
		/usr/local/qt5/include/QtGui/qkeysequence.h \
		/usr/local/qt5/include/QtGui/qevent.h \
		/usr/local/qt5/include/QtCore/qvariant.h \
		/usr/local/qt5/include/QtCore/qmap.h \
		/usr/local/qt5/include/QtCore/qdebug.h \
		/usr/local/qt5/include/QtCore/qtextstream.h \
		/usr/local/qt5/include/QtCore/qlocale.h \
		/usr/local/qt5/include/QtCore/qset.h \
		/usr/local/qt5/include/QtCore/qcontiguouscache.h \
		/usr/local/qt5/include/QtCore/qurl.h \
		/usr/local/qt5/include/QtCore/qurlquery.h \
		/usr/local/qt5/include/QtCore/qfile.h \
		/usr/local/qt5/include/QtCore/qfiledevice.h \
		/usr/local/qt5/include/QtGui/qvector2d.h \
		/usr/local/qt5/include/QtGui/qtouchdevice.h \
		/usr/local/qt5/include/QtWidgets/QSplitter \
		/usr/local/qt5/include/QtWidgets/qsplitter.h \
		/usr/local/qt5/include/QtWidgets/qframe.h \
		/usr/local/qt5/include/QtCore/QVector \
		/usr/local/qt5/include/QtCore/QTextStream \
		src/frontend.h \
		/usr/local/qt5/include/QtWidgets/QWidget \
		src/pad.h \
		/usr/local/qt5/include/QtWidgets/QPushButton \
		/usr/local/qt5/include/QtWidgets/qpushbutton.h \
		/usr/local/qt5/include/QtWidgets/qabstractbutton.h \
		/usr/local/qt5/include/QtGui/qicon.h \
		/usr/local/qt5/include/QtWidgets/QSlider \
		/usr/local/qt5/include/QtWidgets/qslider.h \
		/usr/local/qt5/include/QtWidgets/qabstractslider.h \
		src/backend.h \
		src/sample.h \
		/usr/local/qt5/include/QtCore/QString \
		/usr/local/qt5/include/QtCore/QByteArray \
		src/volume_tab.h \
		src/samples_tab.h \
		/usr/local/qt5/include/QtWidgets/QListWidget \
		/usr/local/qt5/include/QtWidgets/qlistwidget.h \
		/usr/local/qt5/include/QtWidgets/qlistview.h \
		/usr/local/qt5/include/QtWidgets/qabstractitemview.h \
		/usr/local/qt5/include/QtWidgets/qabstractscrollarea.h \
		/usr/local/qt5/include/QtCore/qabstractitemmodel.h \
		/usr/local/qt5/include/QtCore/qitemselectionmodel.h \
		/usr/local/qt5/include/QtWidgets/qabstractitemdelegate.h \
		/usr/local/qt5/include/QtWidgets/qstyleoption.h \
		/usr/local/qt5/include/QtWidgets/qabstractspinbox.h \
		/usr/local/qt5/include/QtGui/qvalidator.h \
		/usr/local/qt5/include/QtCore/qregularexpression.h \
		/usr/local/qt5/include/QtWidgets/qstyle.h \
		/usr/local/qt5/include/QtWidgets/qtabbar.h \
		/usr/local/qt5/include/QtWidgets/qtabwidget.h \
		/usr/local/qt5/include/QtWidgets/qrubberband.h \
		src/buttons_tab.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/frontend.o src/frontend.cpp

.obj/main.o: src/main.cpp /usr/local/qt5/include/QtWidgets/QApplication \
		/usr/local/qt5/include/QtWidgets/qapplication.h \
		/usr/local/qt5/include/QtCore/qcoreapplication.h \
		/usr/local/qt5/include/QtCore/qglobal.h \
		/usr/local/qt5/include/QtCore/qconfig.h \
		/usr/local/qt5/include/QtCore/qfeatures.h \
		/usr/local/qt5/include/QtCore/qsystemdetection.h \
		/usr/local/qt5/include/QtCore/qprocessordetection.h \
		/usr/local/qt5/include/QtCore/qcompilerdetection.h \
		/usr/local/qt5/include/QtCore/qtypeinfo.h \
		/usr/local/qt5/include/QtCore/qtypetraits.h \
		/usr/local/qt5/include/QtCore/qisenum.h \
		/usr/local/qt5/include/QtCore/qsysinfo.h \
		/usr/local/qt5/include/QtCore/qlogging.h \
		/usr/local/qt5/include/QtCore/qflags.h \
		/usr/local/qt5/include/QtCore/qatomic.h \
		/usr/local/qt5/include/QtCore/qbasicatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt5/include/QtCore/qgenericatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt5/include/QtCore/qatomic_msvc.h \
		/usr/local/qt5/include/QtCore/qglobalstatic.h \
		/usr/local/qt5/include/QtCore/qmutex.h \
		/usr/local/qt5/include/QtCore/qnumeric.h \
		/usr/local/qt5/include/QtCore/qversiontagging.h \
		/usr/local/qt5/include/QtCore/qstring.h \
		/usr/local/qt5/include/QtCore/qchar.h \
		/usr/local/qt5/include/QtCore/qbytearray.h \
		/usr/local/qt5/include/QtCore/qrefcount.h \
		/usr/local/qt5/include/QtCore/qnamespace.h \
		/usr/local/qt5/include/QtCore/qarraydata.h \
		/usr/local/qt5/include/QtCore/qstringbuilder.h \
		/usr/local/qt5/include/QtCore/qobject.h \
		/usr/local/qt5/include/QtCore/qobjectdefs.h \
		/usr/local/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt5/include/QtCore/qlist.h \
		/usr/local/qt5/include/QtCore/qalgorithms.h \
		/usr/local/qt5/include/QtCore/qiterator.h \
		/usr/local/qt5/include/QtCore/qhashfunctions.h \
		/usr/local/qt5/include/QtCore/qpair.h \
		/usr/local/qt5/include/QtCore/qbytearraylist.h \
		/usr/local/qt5/include/QtCore/qstringlist.h \
		/usr/local/qt5/include/QtCore/qregexp.h \
		/usr/local/qt5/include/QtCore/qstringmatcher.h \
		/usr/local/qt5/include/QtCore/qcoreevent.h \
		/usr/local/qt5/include/QtCore/qscopedpointer.h \
		/usr/local/qt5/include/QtCore/qmetatype.h \
		/usr/local/qt5/include/QtCore/qvarlengtharray.h \
		/usr/local/qt5/include/QtCore/qcontainerfwd.h \
		/usr/local/qt5/include/QtCore/qobject_impl.h \
		/usr/local/qt5/include/QtCore/qeventloop.h \
		/usr/local/qt5/include/QtGui/qwindowdefs.h \
		/usr/local/qt5/include/QtGui/qwindowdefs_win.h \
		/usr/local/qt5/include/QtCore/qpoint.h \
		/usr/local/qt5/include/QtCore/qsize.h \
		/usr/local/qt5/include/QtGui/qcursor.h \
		/usr/local/qt5/include/QtWidgets/qdesktopwidget.h \
		/usr/local/qt5/include/QtWidgets/qwidget.h \
		/usr/local/qt5/include/QtCore/qmargins.h \
		/usr/local/qt5/include/QtGui/qpaintdevice.h \
		/usr/local/qt5/include/QtCore/qrect.h \
		/usr/local/qt5/include/QtGui/qpalette.h \
		/usr/local/qt5/include/QtGui/qcolor.h \
		/usr/local/qt5/include/QtGui/qrgb.h \
		/usr/local/qt5/include/QtGui/qrgba64.h \
		/usr/local/qt5/include/QtGui/qbrush.h \
		/usr/local/qt5/include/QtCore/qvector.h \
		/usr/local/qt5/include/QtGui/qmatrix.h \
		/usr/local/qt5/include/QtGui/qpolygon.h \
		/usr/local/qt5/include/QtGui/qregion.h \
		/usr/local/qt5/include/QtCore/qdatastream.h \
		/usr/local/qt5/include/QtCore/qiodevice.h \
		/usr/local/qt5/include/QtCore/qline.h \
		/usr/local/qt5/include/QtGui/qtransform.h \
		/usr/local/qt5/include/QtGui/qpainterpath.h \
		/usr/local/qt5/include/QtGui/qimage.h \
		/usr/local/qt5/include/QtGui/qpixelformat.h \
		/usr/local/qt5/include/QtGui/qpixmap.h \
		/usr/local/qt5/include/QtCore/qsharedpointer.h \
		/usr/local/qt5/include/QtCore/qshareddata.h \
		/usr/local/qt5/include/QtCore/qhash.h \
		/usr/local/qt5/include/QtCore/qsharedpointer_impl.h \
		/usr/local/qt5/include/QtGui/qfont.h \
		/usr/local/qt5/include/QtGui/qfontmetrics.h \
		/usr/local/qt5/include/QtGui/qfontinfo.h \
		/usr/local/qt5/include/QtWidgets/qsizepolicy.h \
		/usr/local/qt5/include/QtGui/qkeysequence.h \
		/usr/local/qt5/include/QtGui/qevent.h \
		/usr/local/qt5/include/QtCore/qvariant.h \
		/usr/local/qt5/include/QtCore/qmap.h \
		/usr/local/qt5/include/QtCore/qdebug.h \
		/usr/local/qt5/include/QtCore/qtextstream.h \
		/usr/local/qt5/include/QtCore/qlocale.h \
		/usr/local/qt5/include/QtCore/qset.h \
		/usr/local/qt5/include/QtCore/qcontiguouscache.h \
		/usr/local/qt5/include/QtCore/qurl.h \
		/usr/local/qt5/include/QtCore/qurlquery.h \
		/usr/local/qt5/include/QtCore/qfile.h \
		/usr/local/qt5/include/QtCore/qfiledevice.h \
		/usr/local/qt5/include/QtGui/qvector2d.h \
		/usr/local/qt5/include/QtGui/qtouchdevice.h \
		/usr/local/qt5/include/QtGui/qguiapplication.h \
		/usr/local/qt5/include/QtGui/qinputmethod.h \
		/usr/local/qt5/include/QtCore/QVector \
		/usr/local/qt5/include/QtCore/QTextStream \
		src/frontend.h \
		/usr/local/qt5/include/QtWidgets/QWidget \
		src/pad.h \
		/usr/local/qt5/include/QtWidgets/QPushButton \
		/usr/local/qt5/include/QtWidgets/qpushbutton.h \
		/usr/local/qt5/include/QtWidgets/qabstractbutton.h \
		/usr/local/qt5/include/QtGui/qicon.h \
		/usr/local/qt5/include/QtWidgets/QSlider \
		/usr/local/qt5/include/QtWidgets/qslider.h \
		/usr/local/qt5/include/QtWidgets/qabstractslider.h \
		src/backend.h \
		src/sample.h \
		/usr/local/qt5/include/QtCore/QString \
		/usr/local/qt5/include/QtCore/QByteArray \
		src/constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/main.o src/main.cpp

.obj/pad.o: src/pad.cpp /usr/local/qt5/include/QtWidgets/QPushButton \
		/usr/local/qt5/include/QtWidgets/qpushbutton.h \
		/usr/local/qt5/include/QtWidgets/qabstractbutton.h \
		/usr/local/qt5/include/QtGui/qicon.h \
		/usr/local/qt5/include/QtCore/qglobal.h \
		/usr/local/qt5/include/QtCore/qconfig.h \
		/usr/local/qt5/include/QtCore/qfeatures.h \
		/usr/local/qt5/include/QtCore/qsystemdetection.h \
		/usr/local/qt5/include/QtCore/qprocessordetection.h \
		/usr/local/qt5/include/QtCore/qcompilerdetection.h \
		/usr/local/qt5/include/QtCore/qtypeinfo.h \
		/usr/local/qt5/include/QtCore/qtypetraits.h \
		/usr/local/qt5/include/QtCore/qisenum.h \
		/usr/local/qt5/include/QtCore/qsysinfo.h \
		/usr/local/qt5/include/QtCore/qlogging.h \
		/usr/local/qt5/include/QtCore/qflags.h \
		/usr/local/qt5/include/QtCore/qatomic.h \
		/usr/local/qt5/include/QtCore/qbasicatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt5/include/QtCore/qgenericatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt5/include/QtCore/qatomic_msvc.h \
		/usr/local/qt5/include/QtCore/qglobalstatic.h \
		/usr/local/qt5/include/QtCore/qmutex.h \
		/usr/local/qt5/include/QtCore/qnumeric.h \
		/usr/local/qt5/include/QtCore/qversiontagging.h \
		/usr/local/qt5/include/QtCore/qsize.h \
		/usr/local/qt5/include/QtCore/qnamespace.h \
		/usr/local/qt5/include/QtCore/qlist.h \
		/usr/local/qt5/include/QtCore/qalgorithms.h \
		/usr/local/qt5/include/QtCore/qiterator.h \
		/usr/local/qt5/include/QtCore/qrefcount.h \
		/usr/local/qt5/include/QtCore/qarraydata.h \
		/usr/local/qt5/include/QtCore/qhashfunctions.h \
		/usr/local/qt5/include/QtCore/qchar.h \
		/usr/local/qt5/include/QtCore/qpair.h \
		/usr/local/qt5/include/QtCore/qbytearraylist.h \
		/usr/local/qt5/include/QtCore/qbytearray.h \
		/usr/local/qt5/include/QtCore/qstring.h \
		/usr/local/qt5/include/QtCore/qstringbuilder.h \
		/usr/local/qt5/include/QtCore/qstringlist.h \
		/usr/local/qt5/include/QtCore/qregexp.h \
		/usr/local/qt5/include/QtCore/qstringmatcher.h \
		/usr/local/qt5/include/QtGui/qpixmap.h \
		/usr/local/qt5/include/QtGui/qpaintdevice.h \
		/usr/local/qt5/include/QtGui/qwindowdefs.h \
		/usr/local/qt5/include/QtCore/qobjectdefs.h \
		/usr/local/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt5/include/QtGui/qwindowdefs_win.h \
		/usr/local/qt5/include/QtCore/qrect.h \
		/usr/local/qt5/include/QtCore/qmargins.h \
		/usr/local/qt5/include/QtCore/qpoint.h \
		/usr/local/qt5/include/QtGui/qcolor.h \
		/usr/local/qt5/include/QtGui/qrgb.h \
		/usr/local/qt5/include/QtGui/qrgba64.h \
		/usr/local/qt5/include/QtCore/qsharedpointer.h \
		/usr/local/qt5/include/QtCore/qshareddata.h \
		/usr/local/qt5/include/QtCore/qhash.h \
		/usr/local/qt5/include/QtCore/qsharedpointer_impl.h \
		/usr/local/qt5/include/QtCore/qobject.h \
		/usr/local/qt5/include/QtCore/qcoreevent.h \
		/usr/local/qt5/include/QtCore/qscopedpointer.h \
		/usr/local/qt5/include/QtCore/qmetatype.h \
		/usr/local/qt5/include/QtCore/qvarlengtharray.h \
		/usr/local/qt5/include/QtCore/qcontainerfwd.h \
		/usr/local/qt5/include/QtCore/qobject_impl.h \
		/usr/local/qt5/include/QtGui/qimage.h \
		/usr/local/qt5/include/QtGui/qpixelformat.h \
		/usr/local/qt5/include/QtGui/qtransform.h \
		/usr/local/qt5/include/QtGui/qmatrix.h \
		/usr/local/qt5/include/QtGui/qpolygon.h \
		/usr/local/qt5/include/QtCore/qvector.h \
		/usr/local/qt5/include/QtGui/qregion.h \
		/usr/local/qt5/include/QtCore/qdatastream.h \
		/usr/local/qt5/include/QtCore/qiodevice.h \
		/usr/local/qt5/include/QtCore/qline.h \
		/usr/local/qt5/include/QtGui/qpainterpath.h \
		/usr/local/qt5/include/QtGui/qkeysequence.h \
		/usr/local/qt5/include/QtWidgets/qwidget.h \
		/usr/local/qt5/include/QtGui/qpalette.h \
		/usr/local/qt5/include/QtGui/qbrush.h \
		/usr/local/qt5/include/QtGui/qfont.h \
		/usr/local/qt5/include/QtGui/qfontmetrics.h \
		/usr/local/qt5/include/QtGui/qfontinfo.h \
		/usr/local/qt5/include/QtWidgets/qsizepolicy.h \
		/usr/local/qt5/include/QtGui/qcursor.h \
		/usr/local/qt5/include/QtGui/qevent.h \
		/usr/local/qt5/include/QtCore/qvariant.h \
		/usr/local/qt5/include/QtCore/qmap.h \
		/usr/local/qt5/include/QtCore/qdebug.h \
		/usr/local/qt5/include/QtCore/qtextstream.h \
		/usr/local/qt5/include/QtCore/qlocale.h \
		/usr/local/qt5/include/QtCore/qset.h \
		/usr/local/qt5/include/QtCore/qcontiguouscache.h \
		/usr/local/qt5/include/QtCore/qurl.h \
		/usr/local/qt5/include/QtCore/qurlquery.h \
		/usr/local/qt5/include/QtCore/qfile.h \
		/usr/local/qt5/include/QtCore/qfiledevice.h \
		/usr/local/qt5/include/QtGui/qvector2d.h \
		/usr/local/qt5/include/QtGui/qtouchdevice.h \
		/usr/local/qt5/include/QtWidgets/QSlider \
		/usr/local/qt5/include/QtWidgets/qslider.h \
		/usr/local/qt5/include/QtWidgets/qabstractslider.h \
		/usr/local/qt5/include/QtCore/QTextStream \
		src/pad.h \
		/usr/local/qt5/include/QtWidgets/QWidget \
		src/backend.h \
		src/sample.h \
		/usr/local/qt5/include/QtCore/QString \
		/usr/local/qt5/include/QtCore/QByteArray \
		src/constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/pad.o src/pad.cpp

.obj/samples_tab.o: src/samples_tab.cpp /usr/local/qt5/include/QtWidgets/QVBoxLayout \
		/usr/local/qt5/include/QtWidgets/qboxlayout.h \
		/usr/local/qt5/include/QtWidgets/qlayout.h \
		/usr/local/qt5/include/QtCore/qobject.h \
		/usr/local/qt5/include/QtCore/qobjectdefs.h \
		/usr/local/qt5/include/QtCore/qnamespace.h \
		/usr/local/qt5/include/QtCore/qglobal.h \
		/usr/local/qt5/include/QtCore/qconfig.h \
		/usr/local/qt5/include/QtCore/qfeatures.h \
		/usr/local/qt5/include/QtCore/qsystemdetection.h \
		/usr/local/qt5/include/QtCore/qprocessordetection.h \
		/usr/local/qt5/include/QtCore/qcompilerdetection.h \
		/usr/local/qt5/include/QtCore/qtypeinfo.h \
		/usr/local/qt5/include/QtCore/qtypetraits.h \
		/usr/local/qt5/include/QtCore/qisenum.h \
		/usr/local/qt5/include/QtCore/qsysinfo.h \
		/usr/local/qt5/include/QtCore/qlogging.h \
		/usr/local/qt5/include/QtCore/qflags.h \
		/usr/local/qt5/include/QtCore/qatomic.h \
		/usr/local/qt5/include/QtCore/qbasicatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt5/include/QtCore/qgenericatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt5/include/QtCore/qatomic_msvc.h \
		/usr/local/qt5/include/QtCore/qglobalstatic.h \
		/usr/local/qt5/include/QtCore/qmutex.h \
		/usr/local/qt5/include/QtCore/qnumeric.h \
		/usr/local/qt5/include/QtCore/qversiontagging.h \
		/usr/local/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt5/include/QtCore/qstring.h \
		/usr/local/qt5/include/QtCore/qchar.h \
		/usr/local/qt5/include/QtCore/qbytearray.h \
		/usr/local/qt5/include/QtCore/qrefcount.h \
		/usr/local/qt5/include/QtCore/qarraydata.h \
		/usr/local/qt5/include/QtCore/qstringbuilder.h \
		/usr/local/qt5/include/QtCore/qlist.h \
		/usr/local/qt5/include/QtCore/qalgorithms.h \
		/usr/local/qt5/include/QtCore/qiterator.h \
		/usr/local/qt5/include/QtCore/qhashfunctions.h \
		/usr/local/qt5/include/QtCore/qpair.h \
		/usr/local/qt5/include/QtCore/qbytearraylist.h \
		/usr/local/qt5/include/QtCore/qstringlist.h \
		/usr/local/qt5/include/QtCore/qregexp.h \
		/usr/local/qt5/include/QtCore/qstringmatcher.h \
		/usr/local/qt5/include/QtCore/qcoreevent.h \
		/usr/local/qt5/include/QtCore/qscopedpointer.h \
		/usr/local/qt5/include/QtCore/qmetatype.h \
		/usr/local/qt5/include/QtCore/qvarlengtharray.h \
		/usr/local/qt5/include/QtCore/qcontainerfwd.h \
		/usr/local/qt5/include/QtCore/qobject_impl.h \
		/usr/local/qt5/include/QtWidgets/qlayoutitem.h \
		/usr/local/qt5/include/QtWidgets/qsizepolicy.h \
		/usr/local/qt5/include/QtCore/qrect.h \
		/usr/local/qt5/include/QtCore/qmargins.h \
		/usr/local/qt5/include/QtCore/qsize.h \
		/usr/local/qt5/include/QtCore/qpoint.h \
		/usr/local/qt5/include/QtWidgets/qgridlayout.h \
		/usr/local/qt5/include/QtWidgets/qwidget.h \
		/usr/local/qt5/include/QtGui/qwindowdefs.h \
		/usr/local/qt5/include/QtGui/qwindowdefs_win.h \
		/usr/local/qt5/include/QtGui/qpaintdevice.h \
		/usr/local/qt5/include/QtGui/qpalette.h \
		/usr/local/qt5/include/QtGui/qcolor.h \
		/usr/local/qt5/include/QtGui/qrgb.h \
		/usr/local/qt5/include/QtGui/qrgba64.h \
		/usr/local/qt5/include/QtGui/qbrush.h \
		/usr/local/qt5/include/QtCore/qvector.h \
		/usr/local/qt5/include/QtGui/qmatrix.h \
		/usr/local/qt5/include/QtGui/qpolygon.h \
		/usr/local/qt5/include/QtGui/qregion.h \
		/usr/local/qt5/include/QtCore/qdatastream.h \
		/usr/local/qt5/include/QtCore/qiodevice.h \
		/usr/local/qt5/include/QtCore/qline.h \
		/usr/local/qt5/include/QtGui/qtransform.h \
		/usr/local/qt5/include/QtGui/qpainterpath.h \
		/usr/local/qt5/include/QtGui/qimage.h \
		/usr/local/qt5/include/QtGui/qpixelformat.h \
		/usr/local/qt5/include/QtGui/qpixmap.h \
		/usr/local/qt5/include/QtCore/qsharedpointer.h \
		/usr/local/qt5/include/QtCore/qshareddata.h \
		/usr/local/qt5/include/QtCore/qhash.h \
		/usr/local/qt5/include/QtCore/qsharedpointer_impl.h \
		/usr/local/qt5/include/QtGui/qfont.h \
		/usr/local/qt5/include/QtGui/qfontmetrics.h \
		/usr/local/qt5/include/QtGui/qfontinfo.h \
		/usr/local/qt5/include/QtGui/qcursor.h \
		/usr/local/qt5/include/QtGui/qkeysequence.h \
		/usr/local/qt5/include/QtGui/qevent.h \
		/usr/local/qt5/include/QtCore/qvariant.h \
		/usr/local/qt5/include/QtCore/qmap.h \
		/usr/local/qt5/include/QtCore/qdebug.h \
		/usr/local/qt5/include/QtCore/qtextstream.h \
		/usr/local/qt5/include/QtCore/qlocale.h \
		/usr/local/qt5/include/QtCore/qset.h \
		/usr/local/qt5/include/QtCore/qcontiguouscache.h \
		/usr/local/qt5/include/QtCore/qurl.h \
		/usr/local/qt5/include/QtCore/qurlquery.h \
		/usr/local/qt5/include/QtCore/qfile.h \
		/usr/local/qt5/include/QtCore/qfiledevice.h \
		/usr/local/qt5/include/QtGui/qvector2d.h \
		/usr/local/qt5/include/QtGui/qtouchdevice.h \
		/usr/local/qt5/include/QtCore/QVector \
		/usr/local/qt5/include/QtCore/QTextStream \
		src/samples_tab.h \
		/usr/local/qt5/include/QtWidgets/QWidget \
		/usr/local/qt5/include/QtWidgets/QListWidget \
		/usr/local/qt5/include/QtWidgets/qlistwidget.h \
		/usr/local/qt5/include/QtWidgets/qlistview.h \
		/usr/local/qt5/include/QtWidgets/qabstractitemview.h \
		/usr/local/qt5/include/QtWidgets/qabstractscrollarea.h \
		/usr/local/qt5/include/QtWidgets/qframe.h \
		/usr/local/qt5/include/QtCore/qabstractitemmodel.h \
		/usr/local/qt5/include/QtCore/qitemselectionmodel.h \
		/usr/local/qt5/include/QtWidgets/qabstractitemdelegate.h \
		/usr/local/qt5/include/QtWidgets/qstyleoption.h \
		/usr/local/qt5/include/QtWidgets/qabstractspinbox.h \
		/usr/local/qt5/include/QtGui/qvalidator.h \
		/usr/local/qt5/include/QtCore/qregularexpression.h \
		/usr/local/qt5/include/QtGui/qicon.h \
		/usr/local/qt5/include/QtWidgets/qslider.h \
		/usr/local/qt5/include/QtWidgets/qabstractslider.h \
		/usr/local/qt5/include/QtWidgets/qstyle.h \
		/usr/local/qt5/include/QtWidgets/qtabbar.h \
		/usr/local/qt5/include/QtWidgets/qtabwidget.h \
		/usr/local/qt5/include/QtWidgets/qrubberband.h \
		/usr/local/qt5/include/QtWidgets/QPushButton \
		/usr/local/qt5/include/QtWidgets/qpushbutton.h \
		/usr/local/qt5/include/QtWidgets/qabstractbutton.h \
		src/pad.h \
		/usr/local/qt5/include/QtWidgets/QSlider \
		src/backend.h \
		src/sample.h \
		/usr/local/qt5/include/QtCore/QString \
		/usr/local/qt5/include/QtCore/QByteArray \
		src/constants.h \
		src/select_window.h \
		/usr/local/qt5/include/QtWidgets/QLineEdit \
		/usr/local/qt5/include/QtWidgets/qlineedit.h \
		/usr/local/qt5/include/QtGui/qtextcursor.h \
		/usr/local/qt5/include/QtGui/qtextformat.h \
		/usr/local/qt5/include/QtGui/qpen.h \
		/usr/local/qt5/include/QtGui/qtextoption.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/samples_tab.o src/samples_tab.cpp

.obj/volume_tab.o: src/volume_tab.cpp /usr/local/qt5/include/QtWidgets/QGridLayout \
		/usr/local/qt5/include/QtWidgets/qgridlayout.h \
		/usr/local/qt5/include/QtWidgets/qlayout.h \
		/usr/local/qt5/include/QtCore/qobject.h \
		/usr/local/qt5/include/QtCore/qobjectdefs.h \
		/usr/local/qt5/include/QtCore/qnamespace.h \
		/usr/local/qt5/include/QtCore/qglobal.h \
		/usr/local/qt5/include/QtCore/qconfig.h \
		/usr/local/qt5/include/QtCore/qfeatures.h \
		/usr/local/qt5/include/QtCore/qsystemdetection.h \
		/usr/local/qt5/include/QtCore/qprocessordetection.h \
		/usr/local/qt5/include/QtCore/qcompilerdetection.h \
		/usr/local/qt5/include/QtCore/qtypeinfo.h \
		/usr/local/qt5/include/QtCore/qtypetraits.h \
		/usr/local/qt5/include/QtCore/qisenum.h \
		/usr/local/qt5/include/QtCore/qsysinfo.h \
		/usr/local/qt5/include/QtCore/qlogging.h \
		/usr/local/qt5/include/QtCore/qflags.h \
		/usr/local/qt5/include/QtCore/qatomic.h \
		/usr/local/qt5/include/QtCore/qbasicatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt5/include/QtCore/qgenericatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt5/include/QtCore/qatomic_msvc.h \
		/usr/local/qt5/include/QtCore/qglobalstatic.h \
		/usr/local/qt5/include/QtCore/qmutex.h \
		/usr/local/qt5/include/QtCore/qnumeric.h \
		/usr/local/qt5/include/QtCore/qversiontagging.h \
		/usr/local/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt5/include/QtCore/qstring.h \
		/usr/local/qt5/include/QtCore/qchar.h \
		/usr/local/qt5/include/QtCore/qbytearray.h \
		/usr/local/qt5/include/QtCore/qrefcount.h \
		/usr/local/qt5/include/QtCore/qarraydata.h \
		/usr/local/qt5/include/QtCore/qstringbuilder.h \
		/usr/local/qt5/include/QtCore/qlist.h \
		/usr/local/qt5/include/QtCore/qalgorithms.h \
		/usr/local/qt5/include/QtCore/qiterator.h \
		/usr/local/qt5/include/QtCore/qhashfunctions.h \
		/usr/local/qt5/include/QtCore/qpair.h \
		/usr/local/qt5/include/QtCore/qbytearraylist.h \
		/usr/local/qt5/include/QtCore/qstringlist.h \
		/usr/local/qt5/include/QtCore/qregexp.h \
		/usr/local/qt5/include/QtCore/qstringmatcher.h \
		/usr/local/qt5/include/QtCore/qcoreevent.h \
		/usr/local/qt5/include/QtCore/qscopedpointer.h \
		/usr/local/qt5/include/QtCore/qmetatype.h \
		/usr/local/qt5/include/QtCore/qvarlengtharray.h \
		/usr/local/qt5/include/QtCore/qcontainerfwd.h \
		/usr/local/qt5/include/QtCore/qobject_impl.h \
		/usr/local/qt5/include/QtWidgets/qlayoutitem.h \
		/usr/local/qt5/include/QtWidgets/qsizepolicy.h \
		/usr/local/qt5/include/QtCore/qrect.h \
		/usr/local/qt5/include/QtCore/qmargins.h \
		/usr/local/qt5/include/QtCore/qsize.h \
		/usr/local/qt5/include/QtCore/qpoint.h \
		/usr/local/qt5/include/QtWidgets/qboxlayout.h \
		/usr/local/qt5/include/QtWidgets/qwidget.h \
		/usr/local/qt5/include/QtGui/qwindowdefs.h \
		/usr/local/qt5/include/QtGui/qwindowdefs_win.h \
		/usr/local/qt5/include/QtGui/qpaintdevice.h \
		/usr/local/qt5/include/QtGui/qpalette.h \
		/usr/local/qt5/include/QtGui/qcolor.h \
		/usr/local/qt5/include/QtGui/qrgb.h \
		/usr/local/qt5/include/QtGui/qrgba64.h \
		/usr/local/qt5/include/QtGui/qbrush.h \
		/usr/local/qt5/include/QtCore/qvector.h \
		/usr/local/qt5/include/QtGui/qmatrix.h \
		/usr/local/qt5/include/QtGui/qpolygon.h \
		/usr/local/qt5/include/QtGui/qregion.h \
		/usr/local/qt5/include/QtCore/qdatastream.h \
		/usr/local/qt5/include/QtCore/qiodevice.h \
		/usr/local/qt5/include/QtCore/qline.h \
		/usr/local/qt5/include/QtGui/qtransform.h \
		/usr/local/qt5/include/QtGui/qpainterpath.h \
		/usr/local/qt5/include/QtGui/qimage.h \
		/usr/local/qt5/include/QtGui/qpixelformat.h \
		/usr/local/qt5/include/QtGui/qpixmap.h \
		/usr/local/qt5/include/QtCore/qsharedpointer.h \
		/usr/local/qt5/include/QtCore/qshareddata.h \
		/usr/local/qt5/include/QtCore/qhash.h \
		/usr/local/qt5/include/QtCore/qsharedpointer_impl.h \
		/usr/local/qt5/include/QtGui/qfont.h \
		/usr/local/qt5/include/QtGui/qfontmetrics.h \
		/usr/local/qt5/include/QtGui/qfontinfo.h \
		/usr/local/qt5/include/QtGui/qcursor.h \
		/usr/local/qt5/include/QtGui/qkeysequence.h \
		/usr/local/qt5/include/QtGui/qevent.h \
		/usr/local/qt5/include/QtCore/qvariant.h \
		/usr/local/qt5/include/QtCore/qmap.h \
		/usr/local/qt5/include/QtCore/qdebug.h \
		/usr/local/qt5/include/QtCore/qtextstream.h \
		/usr/local/qt5/include/QtCore/qlocale.h \
		/usr/local/qt5/include/QtCore/qset.h \
		/usr/local/qt5/include/QtCore/qcontiguouscache.h \
		/usr/local/qt5/include/QtCore/qurl.h \
		/usr/local/qt5/include/QtCore/qurlquery.h \
		/usr/local/qt5/include/QtCore/qfile.h \
		/usr/local/qt5/include/QtCore/qfiledevice.h \
		/usr/local/qt5/include/QtGui/qvector2d.h \
		/usr/local/qt5/include/QtGui/qtouchdevice.h \
		/usr/local/qt5/include/QtWidgets/QSlider \
		/usr/local/qt5/include/QtWidgets/qslider.h \
		/usr/local/qt5/include/QtWidgets/qabstractslider.h \
		/usr/local/qt5/include/QtWidgets/QLabel \
		/usr/local/qt5/include/QtWidgets/qlabel.h \
		/usr/local/qt5/include/QtWidgets/qframe.h \
		/usr/local/qt5/include/QtCore/QVector \
		src/volume_tab.h \
		/usr/local/qt5/include/QtWidgets/QWidget \
		src/pad.h \
		/usr/local/qt5/include/QtWidgets/QPushButton \
		/usr/local/qt5/include/QtWidgets/qpushbutton.h \
		/usr/local/qt5/include/QtWidgets/qabstractbutton.h \
		/usr/local/qt5/include/QtGui/qicon.h \
		src/backend.h \
		src/sample.h \
		/usr/local/qt5/include/QtCore/QString \
		/usr/local/qt5/include/QtCore/QByteArray \
		src/constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/volume_tab.o src/volume_tab.cpp

.obj/select_window.o: src/select_window.cpp /usr/local/qt5/include/QtWidgets/QWidget \
		/usr/local/qt5/include/QtWidgets/qwidget.h \
		/usr/local/qt5/include/QtGui/qwindowdefs.h \
		/usr/local/qt5/include/QtCore/qglobal.h \
		/usr/local/qt5/include/QtCore/qconfig.h \
		/usr/local/qt5/include/QtCore/qfeatures.h \
		/usr/local/qt5/include/QtCore/qsystemdetection.h \
		/usr/local/qt5/include/QtCore/qprocessordetection.h \
		/usr/local/qt5/include/QtCore/qcompilerdetection.h \
		/usr/local/qt5/include/QtCore/qtypeinfo.h \
		/usr/local/qt5/include/QtCore/qtypetraits.h \
		/usr/local/qt5/include/QtCore/qisenum.h \
		/usr/local/qt5/include/QtCore/qsysinfo.h \
		/usr/local/qt5/include/QtCore/qlogging.h \
		/usr/local/qt5/include/QtCore/qflags.h \
		/usr/local/qt5/include/QtCore/qatomic.h \
		/usr/local/qt5/include/QtCore/qbasicatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt5/include/QtCore/qgenericatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt5/include/QtCore/qatomic_msvc.h \
		/usr/local/qt5/include/QtCore/qglobalstatic.h \
		/usr/local/qt5/include/QtCore/qmutex.h \
		/usr/local/qt5/include/QtCore/qnumeric.h \
		/usr/local/qt5/include/QtCore/qversiontagging.h \
		/usr/local/qt5/include/QtCore/qobjectdefs.h \
		/usr/local/qt5/include/QtCore/qnamespace.h \
		/usr/local/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt5/include/QtGui/qwindowdefs_win.h \
		/usr/local/qt5/include/QtCore/qobject.h \
		/usr/local/qt5/include/QtCore/qstring.h \
		/usr/local/qt5/include/QtCore/qchar.h \
		/usr/local/qt5/include/QtCore/qbytearray.h \
		/usr/local/qt5/include/QtCore/qrefcount.h \
		/usr/local/qt5/include/QtCore/qarraydata.h \
		/usr/local/qt5/include/QtCore/qstringbuilder.h \
		/usr/local/qt5/include/QtCore/qlist.h \
		/usr/local/qt5/include/QtCore/qalgorithms.h \
		/usr/local/qt5/include/QtCore/qiterator.h \
		/usr/local/qt5/include/QtCore/qhashfunctions.h \
		/usr/local/qt5/include/QtCore/qpair.h \
		/usr/local/qt5/include/QtCore/qbytearraylist.h \
		/usr/local/qt5/include/QtCore/qstringlist.h \
		/usr/local/qt5/include/QtCore/qregexp.h \
		/usr/local/qt5/include/QtCore/qstringmatcher.h \
		/usr/local/qt5/include/QtCore/qcoreevent.h \
		/usr/local/qt5/include/QtCore/qscopedpointer.h \
		/usr/local/qt5/include/QtCore/qmetatype.h \
		/usr/local/qt5/include/QtCore/qvarlengtharray.h \
		/usr/local/qt5/include/QtCore/qcontainerfwd.h \
		/usr/local/qt5/include/QtCore/qobject_impl.h \
		/usr/local/qt5/include/QtCore/qmargins.h \
		/usr/local/qt5/include/QtGui/qpaintdevice.h \
		/usr/local/qt5/include/QtCore/qrect.h \
		/usr/local/qt5/include/QtCore/qsize.h \
		/usr/local/qt5/include/QtCore/qpoint.h \
		/usr/local/qt5/include/QtGui/qpalette.h \
		/usr/local/qt5/include/QtGui/qcolor.h \
		/usr/local/qt5/include/QtGui/qrgb.h \
		/usr/local/qt5/include/QtGui/qrgba64.h \
		/usr/local/qt5/include/QtGui/qbrush.h \
		/usr/local/qt5/include/QtCore/qvector.h \
		/usr/local/qt5/include/QtGui/qmatrix.h \
		/usr/local/qt5/include/QtGui/qpolygon.h \
		/usr/local/qt5/include/QtGui/qregion.h \
		/usr/local/qt5/include/QtCore/qdatastream.h \
		/usr/local/qt5/include/QtCore/qiodevice.h \
		/usr/local/qt5/include/QtCore/qline.h \
		/usr/local/qt5/include/QtGui/qtransform.h \
		/usr/local/qt5/include/QtGui/qpainterpath.h \
		/usr/local/qt5/include/QtGui/qimage.h \
		/usr/local/qt5/include/QtGui/qpixelformat.h \
		/usr/local/qt5/include/QtGui/qpixmap.h \
		/usr/local/qt5/include/QtCore/qsharedpointer.h \
		/usr/local/qt5/include/QtCore/qshareddata.h \
		/usr/local/qt5/include/QtCore/qhash.h \
		/usr/local/qt5/include/QtCore/qsharedpointer_impl.h \
		/usr/local/qt5/include/QtGui/qfont.h \
		/usr/local/qt5/include/QtGui/qfontmetrics.h \
		/usr/local/qt5/include/QtGui/qfontinfo.h \
		/usr/local/qt5/include/QtWidgets/qsizepolicy.h \
		/usr/local/qt5/include/QtGui/qcursor.h \
		/usr/local/qt5/include/QtGui/qkeysequence.h \
		/usr/local/qt5/include/QtGui/qevent.h \
		/usr/local/qt5/include/QtCore/qvariant.h \
		/usr/local/qt5/include/QtCore/qmap.h \
		/usr/local/qt5/include/QtCore/qdebug.h \
		/usr/local/qt5/include/QtCore/qtextstream.h \
		/usr/local/qt5/include/QtCore/qlocale.h \
		/usr/local/qt5/include/QtCore/qset.h \
		/usr/local/qt5/include/QtCore/qcontiguouscache.h \
		/usr/local/qt5/include/QtCore/qurl.h \
		/usr/local/qt5/include/QtCore/qurlquery.h \
		/usr/local/qt5/include/QtCore/qfile.h \
		/usr/local/qt5/include/QtCore/qfiledevice.h \
		/usr/local/qt5/include/QtGui/qvector2d.h \
		/usr/local/qt5/include/QtGui/qtouchdevice.h \
		/usr/local/qt5/include/QtWidgets/QPushButton \
		/usr/local/qt5/include/QtWidgets/qpushbutton.h \
		/usr/local/qt5/include/QtWidgets/qabstractbutton.h \
		/usr/local/qt5/include/QtGui/qicon.h \
		/usr/local/qt5/include/QtWidgets/QListWidget \
		/usr/local/qt5/include/QtWidgets/qlistwidget.h \
		/usr/local/qt5/include/QtWidgets/qlistview.h \
		/usr/local/qt5/include/QtWidgets/qabstractitemview.h \
		/usr/local/qt5/include/QtWidgets/qabstractscrollarea.h \
		/usr/local/qt5/include/QtWidgets/qframe.h \
		/usr/local/qt5/include/QtCore/qabstractitemmodel.h \
		/usr/local/qt5/include/QtCore/qitemselectionmodel.h \
		/usr/local/qt5/include/QtWidgets/qabstractitemdelegate.h \
		/usr/local/qt5/include/QtWidgets/qstyleoption.h \
		/usr/local/qt5/include/QtWidgets/qabstractspinbox.h \
		/usr/local/qt5/include/QtGui/qvalidator.h \
		/usr/local/qt5/include/QtCore/qregularexpression.h \
		/usr/local/qt5/include/QtWidgets/qslider.h \
		/usr/local/qt5/include/QtWidgets/qabstractslider.h \
		/usr/local/qt5/include/QtWidgets/qstyle.h \
		/usr/local/qt5/include/QtWidgets/qtabbar.h \
		/usr/local/qt5/include/QtWidgets/qtabwidget.h \
		/usr/local/qt5/include/QtWidgets/qrubberband.h \
		/usr/local/qt5/include/QtWidgets/QLineEdit \
		/usr/local/qt5/include/QtWidgets/qlineedit.h \
		/usr/local/qt5/include/QtGui/qtextcursor.h \
		/usr/local/qt5/include/QtGui/qtextformat.h \
		/usr/local/qt5/include/QtGui/qpen.h \
		/usr/local/qt5/include/QtGui/qtextoption.h \
		/usr/local/qt5/include/QtCore/QString \
		/usr/local/qt5/include/QtCore/QDir \
		/usr/local/qt5/include/QtCore/qdir.h \
		/usr/local/qt5/include/QtCore/qfileinfo.h \
		/usr/local/qt5/include/QtWidgets/QGridLayout \
		/usr/local/qt5/include/QtWidgets/qgridlayout.h \
		/usr/local/qt5/include/QtWidgets/qlayout.h \
		/usr/local/qt5/include/QtWidgets/qlayoutitem.h \
		/usr/local/qt5/include/QtWidgets/qboxlayout.h \
		/usr/local/qt5/include/QtCore/QFileInfo \
		/usr/local/qt5/include/QtCore/QRegularExpression \
		/usr/local/qt5/include/QtCore/QTextStream \
		src/select_window.h \
		src/samples_tab.h \
		/usr/local/qt5/include/QtCore/QVector \
		src/pad.h \
		/usr/local/qt5/include/QtWidgets/QSlider \
		src/backend.h \
		src/sample.h \
		/usr/local/qt5/include/QtCore/QByteArray
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/select_window.o src/select_window.cpp

.obj/sample.o: src/sample.cpp /usr/local/qt5/include/QtCore/QString \
		/usr/local/qt5/include/QtCore/qstring.h \
		/usr/local/qt5/include/QtCore/qchar.h \
		/usr/local/qt5/include/QtCore/qglobal.h \
		/usr/local/qt5/include/QtCore/qconfig.h \
		/usr/local/qt5/include/QtCore/qfeatures.h \
		/usr/local/qt5/include/QtCore/qsystemdetection.h \
		/usr/local/qt5/include/QtCore/qprocessordetection.h \
		/usr/local/qt5/include/QtCore/qcompilerdetection.h \
		/usr/local/qt5/include/QtCore/qtypeinfo.h \
		/usr/local/qt5/include/QtCore/qtypetraits.h \
		/usr/local/qt5/include/QtCore/qisenum.h \
		/usr/local/qt5/include/QtCore/qsysinfo.h \
		/usr/local/qt5/include/QtCore/qlogging.h \
		/usr/local/qt5/include/QtCore/qflags.h \
		/usr/local/qt5/include/QtCore/qatomic.h \
		/usr/local/qt5/include/QtCore/qbasicatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt5/include/QtCore/qgenericatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt5/include/QtCore/qatomic_msvc.h \
		/usr/local/qt5/include/QtCore/qglobalstatic.h \
		/usr/local/qt5/include/QtCore/qmutex.h \
		/usr/local/qt5/include/QtCore/qnumeric.h \
		/usr/local/qt5/include/QtCore/qversiontagging.h \
		/usr/local/qt5/include/QtCore/qbytearray.h \
		/usr/local/qt5/include/QtCore/qrefcount.h \
		/usr/local/qt5/include/QtCore/qnamespace.h \
		/usr/local/qt5/include/QtCore/qarraydata.h \
		/usr/local/qt5/include/QtCore/qstringbuilder.h \
		/usr/local/qt5/include/QtCore/QVector \
		/usr/local/qt5/include/QtCore/qvector.h \
		/usr/local/qt5/include/QtCore/qalgorithms.h \
		/usr/local/qt5/include/QtCore/qiterator.h \
		/usr/local/qt5/include/QtCore/qlist.h \
		/usr/local/qt5/include/QtCore/qhashfunctions.h \
		/usr/local/qt5/include/QtCore/qpair.h \
		/usr/local/qt5/include/QtCore/qbytearraylist.h \
		/usr/local/qt5/include/QtCore/qstringlist.h \
		/usr/local/qt5/include/QtCore/qregexp.h \
		/usr/local/qt5/include/QtCore/qstringmatcher.h \
		/usr/local/qt5/include/QtCore/qpoint.h \
		/usr/local/qt5/include/QtCore/QTextStream \
		/usr/local/qt5/include/QtCore/qtextstream.h \
		/usr/local/qt5/include/QtCore/qiodevice.h \
		/usr/local/qt5/include/QtCore/qobject.h \
		/usr/local/qt5/include/QtCore/qobjectdefs.h \
		/usr/local/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt5/include/QtCore/qcoreevent.h \
		/usr/local/qt5/include/QtCore/qscopedpointer.h \
		/usr/local/qt5/include/QtCore/qmetatype.h \
		/usr/local/qt5/include/QtCore/qvarlengtharray.h \
		/usr/local/qt5/include/QtCore/qcontainerfwd.h \
		/usr/local/qt5/include/QtCore/qobject_impl.h \
		/usr/local/qt5/include/QtCore/qlocale.h \
		/usr/local/qt5/include/QtCore/qvariant.h \
		/usr/local/qt5/include/QtCore/qmap.h \
		/usr/local/qt5/include/QtCore/qdebug.h \
		/usr/local/qt5/include/QtCore/qhash.h \
		/usr/local/qt5/include/QtCore/qset.h \
		/usr/local/qt5/include/QtCore/qcontiguouscache.h \
		/usr/local/qt5/include/QtCore/qsharedpointer.h \
		/usr/local/qt5/include/QtCore/qshareddata.h \
		/usr/local/qt5/include/QtCore/qsharedpointer_impl.h \
		src/sample.h \
		/usr/local/qt5/include/QtCore/QByteArray \
		src/wav_parser.h \
		/usr/local/qt5/include/QtCore/QFile \
		/usr/local/qt5/include/QtCore/qfile.h \
		/usr/local/qt5/include/QtCore/qfiledevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/sample.o src/sample.cpp

.obj/wav_parser.o: src/wav_parser.cpp /usr/local/qt5/include/QtCore/QList \
		/usr/local/qt5/include/QtCore/qlist.h \
		/usr/local/qt5/include/QtCore/qalgorithms.h \
		/usr/local/qt5/include/QtCore/qglobal.h \
		/usr/local/qt5/include/QtCore/qconfig.h \
		/usr/local/qt5/include/QtCore/qfeatures.h \
		/usr/local/qt5/include/QtCore/qsystemdetection.h \
		/usr/local/qt5/include/QtCore/qprocessordetection.h \
		/usr/local/qt5/include/QtCore/qcompilerdetection.h \
		/usr/local/qt5/include/QtCore/qtypeinfo.h \
		/usr/local/qt5/include/QtCore/qtypetraits.h \
		/usr/local/qt5/include/QtCore/qisenum.h \
		/usr/local/qt5/include/QtCore/qsysinfo.h \
		/usr/local/qt5/include/QtCore/qlogging.h \
		/usr/local/qt5/include/QtCore/qflags.h \
		/usr/local/qt5/include/QtCore/qatomic.h \
		/usr/local/qt5/include/QtCore/qbasicatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_bootstrap.h \
		/usr/local/qt5/include/QtCore/qgenericatomic.h \
		/usr/local/qt5/include/QtCore/qatomic_cxx11.h \
		/usr/local/qt5/include/QtCore/qatomic_msvc.h \
		/usr/local/qt5/include/QtCore/qglobalstatic.h \
		/usr/local/qt5/include/QtCore/qmutex.h \
		/usr/local/qt5/include/QtCore/qnumeric.h \
		/usr/local/qt5/include/QtCore/qversiontagging.h \
		/usr/local/qt5/include/QtCore/qiterator.h \
		/usr/local/qt5/include/QtCore/qrefcount.h \
		/usr/local/qt5/include/QtCore/qarraydata.h \
		/usr/local/qt5/include/QtCore/qhashfunctions.h \
		/usr/local/qt5/include/QtCore/qchar.h \
		/usr/local/qt5/include/QtCore/qpair.h \
		/usr/local/qt5/include/QtCore/qbytearraylist.h \
		/usr/local/qt5/include/QtCore/qbytearray.h \
		/usr/local/qt5/include/QtCore/qnamespace.h \
		/usr/local/qt5/include/QtCore/qstring.h \
		/usr/local/qt5/include/QtCore/qstringbuilder.h \
		/usr/local/qt5/include/QtCore/qstringlist.h \
		/usr/local/qt5/include/QtCore/qregexp.h \
		/usr/local/qt5/include/QtCore/qstringmatcher.h \
		/usr/local/qt5/include/QtCore/QByteArray \
		/usr/local/qt5/include/QtCore/QString \
		src/wav_parser.h \
		/usr/local/qt5/include/QtCore/QFile \
		/usr/local/qt5/include/QtCore/qfile.h \
		/usr/local/qt5/include/QtCore/qfiledevice.h \
		/usr/local/qt5/include/QtCore/qiodevice.h \
		/usr/local/qt5/include/QtCore/qobject.h \
		/usr/local/qt5/include/QtCore/qobjectdefs.h \
		/usr/local/qt5/include/QtCore/qobjectdefs_impl.h \
		/usr/local/qt5/include/QtCore/qcoreevent.h \
		/usr/local/qt5/include/QtCore/qscopedpointer.h \
		/usr/local/qt5/include/QtCore/qmetatype.h \
		/usr/local/qt5/include/QtCore/qvarlengtharray.h \
		/usr/local/qt5/include/QtCore/qcontainerfwd.h \
		/usr/local/qt5/include/QtCore/qobject_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/wav_parser.o src/wav_parser.cpp

.obj/moc_pad.o: .moc/moc_pad.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_pad.o .moc/moc_pad.cpp

.obj/moc_samples_tab.o: .moc/moc_samples_tab.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_samples_tab.o .moc/moc_samples_tab.cpp

.obj/moc_select_window.o: .moc/moc_select_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o .obj/moc_select_window.o .moc/moc_select_window.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

