######################################################################
# Automatically generated by qmake (3.0) Tue Jun 13 12:13:46 2017
######################################################################

TEMPLATE = app
TARGET = launchpad
INCLUDEPATH += .

# Input
HEADERS += buttons_tab.h constants.h frontend.h samples_tab.h volume_tab.h
SOURCES += buttons_tab.cpp frontend.cpp main.cpp samples_tab.cpp volume_tab.cpp

QT += widgets
